const quotes = [
    "Olisin sitä mieltä, että lähetetään kaikki pakolaisneekerit Lappiin lumitöihin. Joulupukkikin tarvitsee mustia tonttuja. Se on tasa-arvoa.",
    "Kaiken maailman Hula-Hula neekerit, puolialastomat kääpiöt sun muut villi-ihmiset ovat vastaanottaneet Suomen hallitukselta miljoonalahjoituksia",
    "Viidakkokansoilta puuttuu tieto ja mistään lahjakuudesta on aivan turha puhuakaan",
    "Kyl se kamalaa on jos joku suomalainenkin nainen ratkeaa johonkin neekeriin.",
    "Turussa hakataan joka viikonloppu ravintola Safarissa mutakuonoja!",
    "10-15 vuoden päästä Yhdysvalloissa on musta enemmistö ja valkoiset joutuvat alistetun kansan asemaan.",
    "Mä vedän turpaan tota saatanan loordia, Antaa tulla vaan, kyllä täältä pesee kyllä.",
    "Yksikään mutakuono ei raiskaa meidän naisiamme, me pidämme siitä huolen!",
    "Me olemme natseja. Me inhoamme mutakuonoja. Heidät kaikki täytyy järjestää pois Euroopasta.",
    "Ei siellä oo mitään poltettu, ei yhtään, älä puhu paskaa",
    "Mmmm, mutta kaikesta huolimatta. Olen kivenkova rasisti, sadisti ja fasisti. Siitä minä nautin. Sääli on sairautta.",
    "En missään tapauksessa ole mikään natsipelle, vaikka näin kommunistit väittääkin.",
    "Turha on elää, turha on kuolla, turha on vanhojen naisten vittuja nuolla, koska todellinen mies on sotilas, juoppo ja pukki. Jokainen mies itkee, nuolee vitun ja vetää käteen, mutta harva sen tunnustaa. Mutta minä natsiupseerina tunnustan ne kaikki.",
    "Natsi-Siitoin valtuustoon",
    "Kuule, me natsit, me jalostamme rotua, mutta me emme hyväksy tällä hetkellä Ruotsin saastaista pakolaispolitiikkaa, koska 90 prosenttia ruotsalaisista ovat homoseksuaaleja ja liian humanisteja.",
    "Kuule, meikäläiselle ei koskaan tule vierasrotuiset kieroilemaan.",
    "Skandinavian jumala Odin johdattaa meitä ikuiseen taisteluun ja minä vannon äitini haudan kautta minä taistelen ensimmäisenä vaikka henkeni vereen asti tämä on velvollisuus pohjoista rotua kohtaan SIEG HEIL!",
    "Skinheadit ovat meidän miehiämme!",
    "Mun mielestä se on erittäin väärin, että tänne tuodaan noita mutakuonoja. Ne ei tee muuta kuin raiskaa meijän naisia.",
    "Vastaavasti me arjalaiset ollaan tietyssä kehitysasteessa. Meillähän ei ole mitään sukulaisuutta Aatamiin ja Eevaan. Meidät on luotu Atlantis-mantereelle, josta me ollaan jouduttu tänne. Jehova taas loi juutalaisen rodun. Kiinalaiset ja japanilaiset ja muut vinosilmät on puolestaan tulleet toiselta planeetalta. Sellaiselta planeetalta, joka oli maan ja Marsin välissä, joka räjähti ja josta on enää jäljellä vain asteroidivyöhyke.",
    "Arjalaisia en ammu. Mutta jos tulee joku muu...",
    "Me olemme suomalaisia patriootteja, uusnatseja, ja myöskin mustalaiset ovat arjalaisia.",
    "Meidän kanssa ei koskaan pelleillä.",
    "Magnumit on täällä aina valmiina.",
    "Mun äiti sano aikoinaan, et naiset on yleensä semmosia, et tota ne vaatii tyhmän miehen, jolla on paljon rahaa ja pitkä kalu.",
    "Irstailija olen kyllä. Olen perverssi. Äitini toivoi minusta teologia, mutta minusta tulikin rivologi.",
    "Jeesus on humanisti.",
    "Mielelläni haistan vittua, ja minulla on tapana vielä nuollakin päälle. Eli jos kiinnostaa...",
    "Devil, I am devil.",
    "I am sick. I want be sick because my god is Lucifer.",
    "Olen okkultisti, ja minä luen harvase ilta iltarukouksen: Jeesus Kristus anna minulle rakkautta ystäviäni kohtaan. Kunnioitettu Lucifer anna minulle tahdonvoimaasi, että pääsisin harmaan kiven lävitse. Saatana, anna minulle saatanallista järkeäsi. Koska Saatana on järjen isä, ja mitä enemmän meillä on järkeä ja oveluutta, sitä paremmin me pärjäämme tässä maailmassa.",
    "Minä tunnen sotilaita, fanaattisia tappajia, sissimajureita, ja ne on kamalia juoppoja ja kauheita pukkeja. Kauheita tappajia. Se liittyy jotenkin yhteen. Meidän puolueesta on 90% kovia ottamaan ja kovia pukkeja. Minullakin on viimeisen kymmenen vuoden aikana suhde 800 eri naisen kanssa.",
    "Emme me voi olettaa, että valtio maksaa tällaisten puliukkojen viinat ja oleskelut kun he asuvat tuolla rannoilla ja kiusaavat ihmisiä.",
    "Mitään avustuksia ei makseta sellaisille ihmisille jotka pystyvät työntekoon. Ainostaan työtä vastaan voi saada korvauksia.",
    "Sanoisin näin, että lesbot pitäisi ottaa kiinni, pistettäisiin käsiraudoilla kädet ja nilkat yhteen ja sitten kun ne pakkonussittaisiin niin kyllä vauvoja tulisi. Ei ne enää sen jälkeen olisikaan lesboja.",
    "Minä olen ollut teatterissa ja vankilassa ja kaikkea ja minä olen nähnyt homoja ja lesboja, se on kamalaa... vedetään toista perseeseen, tulee semmonen ripulinen kyrpä sieltä ulos. Se on inhottavaa.",
    "Homolordi",
    "Ne joilla kalu seisoo parhaiten, ovat otollisia Saatanalle, ja ne, joiden kalu ei seiso, tai seisoo huonosti tarvitsevat lisäharjoittelua orgioiden tai ryhmäsexin avulla. Myös sipulin syönti lisää potenttisuutta.",
    "Uusi testamentti on totta, vanha testamentti on paskaa.",
    "Saatana elää ja voi hyvin.",
    "Henget ilmoitti minulle, että synnyn seuraavassa elämässäni Yhdysvaltoihin. Minusta tulee seuraavassa elämässäni USA:n presidentti. Näin on ilmoitettu.",
    "Mielestäni terve nainen ei saisi tehdä aborttia.",
    "Siihen aikaan sai tavata vaimoa, muttei panna. Nykyään on vuokrasellit, jossa voi panna. Oli pakko vetää käteen kolme kertaa päivässä, että kunto säilyi. Ellen mä olisi sitä tehnyt silloin ni ei mulla enää kyrpä seisois. Mä oon aina ollu kova kullimies.",
    "Kettutytöt ja eläinaktivistit on hulluja. Turkistarhaajille olisi annettava oikeus miinoittaa turkistarhansa terroristien varalta.",
    "Tilanne on se et ku mä olen kasvattanut koiria. Jos sä annat koirille ruokaa, se haistaa ennen kuin se maistaa ja mä tunnen terveen naisen heti tuoksusta, kun nainen ottaa housut pois. 30 sentin päästä tuntee hajusta onko nainen terve ja se on pitänyt mulla hei.",
    "Paljon pilasit, kaiken munasit, nyt pillusi on kylmennyt",
    "Minun täytyy sanoa kyllä Tarja Halosesta en diggaa lainkaan. Hän on ollut seksuaalisen tasa-arvoliiton lakimies. Hän kannattaa homoja ja lesboja. Hänellä oli tytär, joka ei ole hänen. Asui Arajärven kanssa avoliitossa.",
];

module.exports = quotes;